// Generated by `pnpm optimize:images`. Maps source filename → base64 blurDataURL.
// Falls back to a neutral 1x1 placeholder when an image hasn't been processed.
import data from "../public/images-optimized/blur-data.json" with { type: "json" };

const fallback =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxIDEiPjxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9IiNlNWUxZDgiLz48L3N2Zz4=";

export function blurFor(image: string): string {
  const map = data as Record<string, string>;
  return map[image] ?? fallback;
}
